name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo "Installing core dependencies..."
        pip install --verbose --timeout 300 fastapi==0.115.0 uvicorn==0.32.0 requests==2.32.0 python-dotenv==1.0.0 pydantic==2.5.2 pytest==7.4.3
        echo "Installing ML dependencies..."  
        pip install --verbose --timeout 300 scikit-learn==1.3.2 pandas==2.1.4 numpy==1.24.4 sqlalchemy==2.0.23
        echo "Installing other dependencies..."
        pip install --verbose --timeout 300 loguru==0.7.2
        echo "Installing heavy dependencies (may take longer)..."
        pip install --verbose --timeout 600 mlflow==2.8.1 prefect>=3.1 streamlit==1.28.1
      timeout-minutes: 20
    
    - name: Run tests
      run: |
        pytest test_app.py -v
      env:
        API_KEY: test-key-for-ci
        PERFORMANCE_THRESHOLD: 0.8
        MLFLOW_TRACKING_URI: file:///tmp/mlflow
    
    - name: Test app startup
      run: |
        python -c "import app; print('App imports successfully')"
      env:
        API_KEY: test-key-for-ci
        PERFORMANCE_THRESHOLD: 0.8
        MLFLOW_TRACKING_URI: file:///tmp/mlflow 