name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest test_app.py -v
      env:
        API_KEY: test-key-for-ci
        PERFORMANCE_THRESHOLD: 0.8
        MLFLOW_TRACKING_URI: file:///tmp/mlflow
    
    - name: Test app startup
      run: |
        python -c "import app; print('App imports successfully')"
      env:
        API_KEY: test-key-for-ci
        PERFORMANCE_THRESHOLD: 0.8
        MLFLOW_TRACKING_URI: file:///tmp/mlflow 